server:
  port: 5677

spring:
  application:
    name: '@name@'
    description: '@description@'
    url: '@url@'
    version: '@version@'

springdoc:
  swagger-ui:
    enabled: true
    tags-sorter: 'alpha'

eureka:
  client:
    enabled: false
    eureka-server-connect-timeout-seconds: 100
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
    enabled: false
